language: ruby
rvm:
  - 1.9.3
  - 2.0.0

env:
  - RAILS_VERSION=3.0.20
  - RAILS_VERSION=3.1.12
  - RAILS_VERSION=3.2.3
  - RAILS_VERSION=3.2.15
  - RAILS_VERSION=3.2.15 DB_CHARMER_GEM=1.9.0
  - RAILS_VERSION=4.0.1

notifications:
  recipients:
    - alexey@kovyrin.net

script: ./ci_build

# Whitelist branches to test
branches:
  only:
    - master
    - rails4

# Build matrix configuration
matrix:
  exclude:
    # Do not run Rails 3.0 tests on ruby 2.0
    - rvm: 2.0.0
      env: RAILS_VERSION=3.0.20

    # Do not run Rails 3.1 tests on ruby 2.0
    - rvm: 2.0.0
      env: RAILS_VERSION=3.1.12

    # Do not run early Rails 3.2 tests on ruby 2.0
    - rvm: 2.0.0
      env: RAILS_VERSION=3.2.3
