language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3

env:
  - RAILS_VERSION=2.x
  - RAILS_VERSION=3.0.17
  - RAILS_VERSION=3.1.8
  - RAILS_VERSION=3.2.3
  - RAILS_VERSION=3.2.10
  - RAILS_VERSION=3.2.9 DB_CHARMER_GEM=1.8.0

notifications:
  recipients:
    - alexey@kovyrin.net

script: ./ci_build

# Whitelist branches to test
branches:
  only:
    - master

# Build matrix configuration
matrix:
  exclude:
    # Do not run Rails 2.x tests on ruby 1.9
    - rvm: 1.9.3
      env: RAILS_VERSION=2.x
