pygments: true
auto: true
server: true
permalink: none

#baseurl: /

exclude:
 - Rakefile

title: DbCharmer - Connection Magic for ActiveRecord
description: DbCharmer is a simple yet powerful plugin for ActiveRecord that significantly extends its ability to work with multiple databases and/or database servers.

author:
  name: Oleksiy Kovyrin
  email: alexey@kovyrin.net

